name: ecdsa
description: Package ecdsa implements the Elliptic Curve Digital Signature Algorithm, as defined in FIPS 186-3.
version: 0.1.1
homepage: https://github.com/c0mm4nd/dart-ecdsa

environment:
  sdk: '>=2.12.0 <4.0.0'

# dependencies:
#   path: ^1.8.0

dev_dependencies:
  pedantic: ^1.10.0
  test: ^1.16.0
dependencies: 
  crypto: ^3.0.1
  elliptic: ^0.3.10
  ninja_asn1: ^2.0.0
